export const statuses = {
    STATUS_NOT_INITIALIZED: 'STATUS_NOT_INITIALIZED',
    STATUS_IN_PROGRESS: 'STATUS_IN_PROGRESS',
    STATUS_SUCCESS: 'STATUS_SUCCESS',
    STATUS_ERROR: 'STATUS_ERROR'
};
